name: Code Linting

on:
  pull_request:
    paths:
      - '**/*.cs'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore Backend/CarRentalAPI/CarRental.sln

      - name: Format code
        run: dotnet format Backend/CarRentalAPI/CarRental.sln

      - name: Analyze code
        run: dotnet build Backend/CarRentalAPI/CarRental.sln > build_errors.log 2>&1 